### ISSUE TITLE
German Version

### ISSUE THREAD

**Issue by xremix** [behoernchen/Time-in-Words#2]
Hi,

I'm a big fan of your widget and use it for years now. I immediately wanted to have a german version too. So I modified your code to use german words that time and now decided to publish the code on Github (maybe a couple of years to late :-) ) but just wanted to make you aware of this:
https://github.com/xremix/Uhrzeit-In-Worten

I linked to your version and your name is also in the source code.

I'm going to close this Issue immediatly.

**Comment by raphaelhanneken** [comment]
Servus @xremix! Sehr cool! Vielen Dank, dass du mich teilhaben lässt. 👍🇩🇪
